Chat:
  BlackListedCommands:
  - msg
  - tell
  - m
  - r
  - reply
WorldSettings:
  DisableBlockBreak: true
  DisableBlockPlace: true
  DisableItemPickup: true
  DisableChat: true
  DisableVisible: true
database:
  engine: sqlite
  host: localhost
  port: 3306
  user: root
  password: 'yourpassword'
  database: limbo
  prefix: lb_
  enable-ssl: false
  pool:
    max-pool-size: 10
    connection-timeout: 25
    max-lifetime: 1800
settings:
  proxy: false;